
###

http://localhost:3344/main

###

PATCH http://localhost:3344/main/62c81d400e077835321e0796
Content-Type: application/json
Accept: application/json

{
  "value": "3"
}

### auth

POST http://localhost:3344/authentication
Content-Type: application/json
Accept: application/json

{
  "strategy": "local",
  "email": "admin@nikolav.rs",
  "password": "122333"
}

### auth.create

POST http://localhost:3344/users
Content-Type: application/json
Accept: application/json

{
  "name": "user.19",
  "email": "user.19@nikolav.rs",
  "password": "122333"
}

###
