
###

http://localhost:3344/main

###

POST http://localhost:3344/main
Content-Type: application/json
Accept: application/json

{
  "name": "app.url",
  "value": ""
}

### auth

POST http://localhost:3344/authentication
Content-Type: application/json
Accept: application/json

{
  "strategy": "local",
  "email": "admin@nikolav.rs",
  "password": "122333"
}

### auth.create

POST http://localhost:3344/users
Content-Type: application/json
Accept: application/json

{
  "name": "user.19",
  "email": "user.19@nikolav.rs",
  "password": "122333"
}

###
